name: reviewdog
on: [pull_request]
jobs:
  biome:
    name: runner / Biome
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - uses: mongolyy/reviewdog-action-biome@v2.5.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_level: error
          level: info